### ISSUE TITLE
database mappings defined in json

### ISSUE THREAD

**Issue by joaquimrcarvalho** [time-link/timelink-kleio#24]
```json
{
    "mappings": [
        {
            "name": "entity",
            "class": "entity"
        },
        {
            "name": "person",
            "class": "person"
        },
        {
            "name": "object",
            "class": "object"
        }
    ],
    "classes": [
        {
            "name": "person",
            "super": "entity",
            "table": "persons",
            "attributes": [
                {
                    "name": "id",
                    "column": "id",
                    "baseclass": "id",
                    "coltype": "varchar",
                    "colsize": 64,
                    "colprecision": 0,
                    "pkey": 1
                }
            ]
        }
    ]
}
```

**Comment by joaquimrcarvalho** [comment]
This would affect a few lines: https://github.com/time-link/timelink-kleio/blob/joaquimrcarvalho/issue16/src/gactoxml.pl#L1700-L1703

And two new predicates: mappings_from_json, classes_from_json.

**Comment by joaquimrcarvalho** [comment]
See https://www.mssqltips.com/sqlservertip/6270/save-sql-server-database-structure-as-json/.

**Comment by joaquimrcarvalho** [comment]
This is not a good idea, except for data exchange between apps. For user defined mappings use YAML

**Comment by joaquimrcarvalho** [comment]
This is user configuration information. Should be in YAML:

```YAML
# Mapping connect the groups in the source oriented model
#  to entities in the person oriented model
# Mapping files contain a list of "group"  and "entity" elements
# Entities are used to create new classes in the person oriented model
# and are only necessary if a group contains information not present in the
# base Person Oriented Model
- mapping:   # this assertion should go to str file as an attribute of the group
    name: minutes
    class: minutes
- class:
    name: minutes
    extends: act
    table: minutes
    description: >
      This class represents the minutes of a meeting.
      It is a subclass of the class act.
    attributes:
      - name: id  # name of the attribute in class
        column: id  # name of the columns in the table
        extends: id  # element class in the source model
        type: string  # type for column
        size: 64  # size of the column
        pkey: true #
      - name: the_day
        colum: the_day
        type: number
        size: 2
        precision: 0  # number of decimal places
        extends: day
      - name: the_month
        type: number
        extends: month
      - name: the_year
        column: the_year
        type: number
        extends: year
      - name: summary
        type: string
        extends: text
        size: 32768
      - name: pages  # pages in the minutes book
        type: string
        size: 64
      - name: obs  # any other observation
        type: text
- mapping:   # a synonym for the minutes class
    name: acta
    class: minutes
- mapping:  # a synonym for the minutes class
    name: amz
    class: minutes
```

In Prolog, one line parsing:

```prolog
[yaml{mapping:yaml{class:"minutes",name:"minutes"}},
  yaml{ class:yaml{ attributes:[ yaml{column:"id",extends:"id",name:"id",pkey:true,size:64,type:"string"},
                                 yaml{colum:"the_day",extends:"day",name:"the_day",precision:0,size:2,type:"number"},
                                 yaml{extends:"month",name:"the_month",type:"number"},
                                 yaml{column:"the_year",extends:"year",name:"the_year",type:"number"},
                                 yaml{extends:"text",name:"summary",size:32768,type:"string"},
                                 yaml{name:"pages",size:64,type:"string"},
                                 yaml{name:"obs",type:"text"}
                               ],
                    description:"This class represents the minutes of a meeting. It is a subclass of the class act.\n",
                    extends:"act",
                    name:"minutes",
                    table:"minutes"
                  }
      },
  yaml{mapping:yaml{class:"minutes",name:"acta"}},
  yaml{mapping:yaml{class:"minutes",name:"amz"}}
]
```
