### ISSUE TITLE
structure files in YAML

### ISSUE THREAD

**Issue by joaquimrcarvalho** [time-link/timelink-kleio#48]
Yaml is designed for configuration files and provides convent constructs for Kleio str files:

```yaml
- extends: system.yml  # read the definitions in system.yml before
# Base data types
- element:
    name: number
- element:
    name: string64
- element: {name: string256} # alternative syntax
- element:
    name: text

# Base groups
- group:
    name: kleio
    description: >
      This is the top level group of Kleio files.
      Specific historical sources must be added
      to the part parameter of this group.
    position:
      - structure
      - translator
    also:
      - autorels
      - obs
      - prefix
      - translations
    includes:
      - historical-source
      - fonte
      - authority-register
      - identifications
      - link
- group:
    name: historical-source
    position: [id,year,type,ref] # alternative syntax
    guaranteed: [id]
    includes: [historical-act]
```

This is parsed in python with a single like of code:

```python
path = 'tests/timelink-home/projects/test-project/structures/yaml/sample-stru.yml'
with open(path) as stream:
    pyaml = yaml.full_load(stream)

pprint(pyaml)
```
```python
[{'extends': 'system.yml'},
 {'element': {'name': 'number'}},
 {'element': {'name': 'string64'}},
 {'element': {'name': 'string256'}},
 {'element': {'name': 'text'}},
 {'group': {'also': ['autorels', 'obs', 'prefix', 'translations'],
            'description': 'This is the top level group of Kleio files. '
                           'Specific historical sources must be added to the '
                           'part parameter of this group.\n',
            'includes': ['historical-source',
                         'fonte',
                         'authority-register',
                         'identifications',
                         'link'],
            'name': 'kleio',
            'position': ['structure', 'translator']}},
 {'group': {'guaranteed': ['id'],
            'includes': ['historical-act'],
            'name': 'historical-source',
            'position': ['id', 'year', 'type', 'ref']}}]
```
