### ISSUE TITLE
mapping files in YAML

### ISSUE THREAD

**Issue by joaquimrcarvalho** [time-link/timelink-kleio#50]
The solution to user defined mappings is to use YAML:

```yaml
# Mappings connect the groups in the source oriented model
#  to entities in the person oriented model
# Mapping files contain a list of "group"  and "entity" elements
# Entities are used to create new classes in the person oriented model
# and are only necessary if a group contains information not present in the
# base Person Oriented Model
- group:
    name: minutes
    class: minutes
- entity:
    name: minutes
    extends: act
    table: minutes
    description: >
      This entities represents the minutes of a meeting.
      It is a subclass of the class act.
    attributes:
      - name: id  # name of the attribute in class
        column: id  # name of the columns in the table
        element_class: id  # element class in the associated group
        type: string  # type for column
        size: 64  # size of the column
        pkey: true #
      - name: the_day
        colum: the_day
        type: number
        size: 2
        precision: 0  # number of decimal places
        element_class: day
      - name: the_month
        type: number
        element_class: month
      - name: the_year
        column: the_year
        type: number
        element_class: year
      - name: summary
        type: string
        element_class: text
        size: 32768
      - name: pages  # pages in the minutes book
        type: string
        size: 64
      - name: obs  # any other observation
        type: text
- group:   # a synonym for the minutes class
    name: acta
    class: minutes
- group:  # a synonym for the minutes class
    name: amz
    class: minutes
```
